<?php
$finance_tipo = array(
  array('id' => '1','codigo_conta' => '1','classificacao_conta' => '1','nome_conta' => 'ATIVO','tipo_conta' => 'S'),
  array('id' => '2','codigo_conta' => '2','classificacao_conta' => '11','nome_conta' => 'ATIVO CIRCULANTE','tipo_conta' => 'S'),
  array('id' => '3','codigo_conta' => '3','classificacao_conta' => '111','nome_conta' => 'DISPONÍVEL','tipo_conta' => 'S'),
  array('id' => '4','codigo_conta' => '4','classificacao_conta' => '11101','nome_conta' => 'CAIXA','tipo_conta' => 'S'),
  array('id' => '5','codigo_conta' => '5','classificacao_conta' => '1110100001','nome_conta' => 'CAIXA GERAL','tipo_conta' => 'A'),
  array('id' => '6','codigo_conta' => '6','classificacao_conta' => '1110100002','nome_conta' => 'FUNDO FIXO DE CAIXA','tipo_conta' => 'A'),
  array('id' => '7','codigo_conta' => '7','classificacao_conta' => '11102','nome_conta' => 'BANCOS CONTA MOVIMENTO','tipo_conta' => 'S'),
  array('id' => '8','codigo_conta' => '8','classificacao_conta' => '1110200001','nome_conta' => 'BANCO INTER','tipo_conta' => 'A'),
  array('id' => '9','codigo_conta' => '582','classificacao_conta' => '1110200002','nome_conta' => 'BANCO 2','tipo_conta' => 'A'),
  array('id' => '10','codigo_conta' => '584','classificacao_conta' => '1110200003','nome_conta' => 'BANCO 3','tipo_conta' => 'A'),
  array('id' => '11','codigo_conta' => '9','classificacao_conta' => '11103','nome_conta' => 'APLICAÇÕES FINANCEIRAS','tipo_conta' => 'S'),
  array('id' => '12','codigo_conta' => '10','classificacao_conta' => '1110300001','nome_conta' => 'APLICAÇÃO BANCO INTER','tipo_conta' => 'A'),
  array('id' => '13','codigo_conta' => '11','classificacao_conta' => '1110300002','nome_conta' => 'APLICAÇÃO 2','tipo_conta' => 'A'),
  array('id' => '14','codigo_conta' => '12','classificacao_conta' => '112','nome_conta' => 'CLIENTES','tipo_conta' => 'S'),
  array('id' => '15','codigo_conta' => '13','classificacao_conta' => '11201','nome_conta' => 'DUPLICATAS A RECEBER','tipo_conta' => 'S'),
  array('id' => '16','codigo_conta' => '14','classificacao_conta' => '1120100001','nome_conta' => 'CLIENTES DIVERSOS','tipo_conta' => 'A'),
  array('id' => '17','codigo_conta' => '15','classificacao_conta' => '1120100002','nome_conta' => 'CLIENTES ','tipo_conta' => 'A'),
  array('id' => '18','codigo_conta' => '16','classificacao_conta' => '11202','nome_conta' => '(-) DUPLICATAS DESCONTADAS','tipo_conta' => 'S'),
  array('id' => '19','codigo_conta' => '504','classificacao_conta' => '1120200001','nome_conta' => '(-) DUPLICATA DESCONTADA','tipo_conta' => 'A'),
  array('id' => '20','codigo_conta' => '17','classificacao_conta' => '11203','nome_conta' => 'CRÉDITOS VENCIDOS E NÃO LIQUIDADOS','tipo_conta' => 'S'),
  array('id' => '21','codigo_conta' => '505','classificacao_conta' => '1120300001','nome_conta' => 'PDD','tipo_conta' => 'A'),
  array('id' => '22','codigo_conta' => '18','classificacao_conta' => '113','nome_conta' => 'OUTROS CRÉDITOS','tipo_conta' => 'S'),
  array('id' => '23','codigo_conta' => '61','classificacao_conta' => '113010','nome_conta' => 'EMPRESTIMOS CONCEDIDOS','tipo_conta' => 'S'),
  array('id' => '24','codigo_conta' => '62','classificacao_conta' => '1130100001','nome_conta' => 'EMPRESTIMO','tipo_conta' => 'A'),
  array('id' => '25','codigo_conta' => '506','classificacao_conta' => '1130100002','nome_conta' => 'OUTROS VALORES','tipo_conta' => 'A'),
  array('id' => '26','codigo_conta' => '20','classificacao_conta' => '11302','nome_conta' => 'TÍTULOS A RECEBER','tipo_conta' => 'S'),
  array('id' => '27','codigo_conta' => '21','classificacao_conta' => '11303','nome_conta' => 'CHEQUES EM COBRANÇA E A COMPENSAR','tipo_conta' => 'S'),
  array('id' => '28','codigo_conta' => '507','classificacao_conta' => '1130300001','nome_conta' => 'CHEQUES A COMPENSAR','tipo_conta' => 'A'),
  array('id' => '29','codigo_conta' => '508','classificacao_conta' => '1130300002','nome_conta' => 'VALOR A CLASSIFICAR','tipo_conta' => 'A'),
  array('id' => '30','codigo_conta' => '22','classificacao_conta' => '11304','nome_conta' => 'DIVIDENDOS A RECEBER','tipo_conta' => 'S'),
  array('id' => '31','codigo_conta' => '23','classificacao_conta' => '11305','nome_conta' => 'ADIANTAMENTOS A FORNECEDORES','tipo_conta' => 'S'),
  array('id' => '32','codigo_conta' => '509','classificacao_conta' => '1130500001','nome_conta' => 'ADIANTAMENTO FORNECEDOR','tipo_conta' => 'A'),
  array('id' => '33','codigo_conta' => '613','classificacao_conta' => '1130500002','nome_conta' => 'ADIANTAMENTO DE IMPORTAÇÃO ','tipo_conta' => 'A'),
  array('id' => '34','codigo_conta' => '24','classificacao_conta' => '11306','nome_conta' => 'ADIANTAMENTO A EMPREGADOS','tipo_conta' => 'S'),
  array('id' => '35','codigo_conta' => '25','classificacao_conta' => '1130600001','nome_conta' => 'ADIANTAMENTO DE SALÁRIO','tipo_conta' => 'A'),
  array('id' => '36','codigo_conta' => '26','classificacao_conta' => '1130600002','nome_conta' => 'ADIANTAMENTO DE 13º SALÁRIO','tipo_conta' => 'A'),
  array('id' => '37','codigo_conta' => '63','classificacao_conta' => '1130600003','nome_conta' => 'ADIANTAMENTO DE FÉRIAS','tipo_conta' => 'A'),
  array('id' => '38','codigo_conta' => '57','classificacao_conta' => '1130600004','nome_conta' => 'ADIANTAMENTO PARA VIAGEM','tipo_conta' => 'A'),
  array('id' => '39','codigo_conta' => '58','classificacao_conta' => '1130600005','nome_conta' => 'ADIANTAMENTO DE COMISSÃO','tipo_conta' => 'A'),
  array('id' => '40','codigo_conta' => '27','classificacao_conta' => '11307','nome_conta' => 'EMPRÉSTIMO A SÓCIOS','tipo_conta' => 'S'),
  array('id' => '41','codigo_conta' => '510','classificacao_conta' => '1130700001','nome_conta' => 'EMPRESTIMO A SÓCIOS','tipo_conta' => 'A'),
  array('id' => '42','codigo_conta' => '731','classificacao_conta' => '1130700002','nome_conta' => 'EMPRESTIMO SOCIO 1','tipo_conta' => 'A'),
  array('id' => '43','codigo_conta' => '28','classificacao_conta' => '11308','nome_conta' => 'TRIBUTOS A RECUPERAR/COMPENSAR','tipo_conta' => 'S'),
  array('id' => '44','codigo_conta' => '29','classificacao_conta' => '1130800001','nome_conta' => 'IMPOSTOS RETIDOS LEI 10.833','tipo_conta' => 'A'),
  array('id' => '45','codigo_conta' => '30','classificacao_conta' => '1130800002','nome_conta' => 'ICMS A COMPENSAR','tipo_conta' => 'A'),
  array('id' => '46','codigo_conta' => '31','classificacao_conta' => '1130800003','nome_conta' => 'IRPJ A RECUPERAR','tipo_conta' => 'A'),
  array('id' => '47','codigo_conta' => '32','classificacao_conta' => '1130800004','nome_conta' => 'IMPOSTO DE RENDA S/ APLICAÇÃO FINANCEIRA','tipo_conta' => 'A'),
  array('id' => '48','codigo_conta' => '33','classificacao_conta' => '1130800005','nome_conta' => 'CSSL A COMPENSAR','tipo_conta' => 'A'),
  array('id' => '49','codigo_conta' => '34','classificacao_conta' => '1130800006','nome_conta' => 'TRIBUTOS PAGOS A MAIOR OU INDEVIDAMENTE','tipo_conta' => 'A'),
  array('id' => '50','codigo_conta' => '35','classificacao_conta' => '1130800007','nome_conta' => 'CONTRIBUIÇÃO SOCIAL RETIDO A COMPENSAR','tipo_conta' => 'A'),
  array('id' => '51','codigo_conta' => '36','classificacao_conta' => '1130800008','nome_conta' => 'COFINS RETIDO A COMPENSAR','tipo_conta' => 'A'),
  array('id' => '52','codigo_conta' => '37','classificacao_conta' => '1130800009','nome_conta' => 'PIS RETIDO A COMPENSAR','tipo_conta' => 'A'),
  array('id' => '53','codigo_conta' => '38','classificacao_conta' => '1130800010','nome_conta' => 'INSS A COMPENSAR','tipo_conta' => 'A'),
  array('id' => '54','codigo_conta' => '39','classificacao_conta' => '1130800011','nome_conta' => 'BÔNUS DE ADIMPLÊNCIA FISCAL A COMPENSAR','tipo_conta' => 'A'),
  array('id' => '55','codigo_conta' => '40','classificacao_conta' => '1130800012','nome_conta' => 'COFINS A RECUPERAR','tipo_conta' => 'A'),
  array('id' => '56','codigo_conta' => '41','classificacao_conta' => '1130800013','nome_conta' => 'PIS A RECUPERAR','tipo_conta' => 'A'),
  array('id' => '57','codigo_conta' => '42','classificacao_conta' => '1130800014','nome_conta' => 'COFINS A RECUPERAR - CRÉDITO PRESUMIDO','tipo_conta' => 'A'),
  array('id' => '58','codigo_conta' => '43','classificacao_conta' => '1130800015','nome_conta' => 'PIS RECUPERAR - CRÉDITO PRESUMIDO','tipo_conta' => 'A'),
  array('id' => '59','codigo_conta' => '476','classificacao_conta' => '1130800016','nome_conta' => 'ISS A RECUPERAR','tipo_conta' => 'A'),
  array('id' => '60','codigo_conta' => '44','classificacao_conta' => '11309','nome_conta' => 'JUROS SOBRE O CAPITAL PRÓPRIO','tipo_conta' => 'S'),
  array('id' => '61','codigo_conta' => '45','classificacao_conta' => '1130900001','nome_conta' => 'JUROS SOBRE O CAPITAL PRÓPRIO A RECEBER','tipo_conta' => 'A'),
  array('id' => '62','codigo_conta' => '46','classificacao_conta' => '114','nome_conta' => 'ADIANTAMENTOS / EMPRESTIMOS','tipo_conta' => 'S'),
  array('id' => '63','codigo_conta' => '47','classificacao_conta' => '11401','nome_conta' => 'ADIANTAMENTOS PARA SOCIOS','tipo_conta' => 'S'),
  array('id' => '64','codigo_conta' => '48','classificacao_conta' => '1140100001','nome_conta' => 'DANIEL WEBERTH PEREIRA SOUZA','tipo_conta' => 'A'),
  array('id' => '65','codigo_conta' => '580','classificacao_conta' => '1140100002','nome_conta' => 'SOCIO 2','tipo_conta' => 'A'),
  array('id' => '66','codigo_conta' => '598','classificacao_conta' => '1140100003','nome_conta' => 'SOCIO 3','tipo_conta' => 'A'),
  array('id' => '67','codigo_conta' => '644','classificacao_conta' => '11402','nome_conta' => 'ADIANTAMENTO PARA IMPORTAÇÃO ','tipo_conta' => 'S'),
  array('id' => '68','codigo_conta' => '645','classificacao_conta' => '1140200001','nome_conta' => 'ADIANTAMENTO 1','tipo_conta' => 'A'),
  array('id' => '69','codigo_conta' => '647','classificacao_conta' => '1140200002','nome_conta' => 'ADIANTAMENTO 2','tipo_conta' => 'A'),
  array('id' => '70','codigo_conta' => '49','classificacao_conta' => '11403','nome_conta' => 'ADIANTAMENTOS PARA VIAGENS','tipo_conta' => 'S'),
  array('id' => '71','codigo_conta' => '52','classificacao_conta' => '1140300001','nome_conta' => 'ADIANTAMENTOS PARA VIAGENS','tipo_conta' => 'A'),
  array('id' => '72','codigo_conta' => '50','classificacao_conta' => '11404','nome_conta' => 'DEBÊNTURES','tipo_conta' => 'S'),
  array('id' => '73','codigo_conta' => '51','classificacao_conta' => '1140400001','nome_conta' => 'VALOR NOMINAL','tipo_conta' => 'A'),
  array('id' => '74','codigo_conta' => '53','classificacao_conta' => '115','nome_conta' => 'ESTOQUE','tipo_conta' => 'S'),
  array('id' => '75','codigo_conta' => '54','classificacao_conta' => '11501','nome_conta' => 'MERCADORIAS, PRODUTOS E INSUMOS','tipo_conta' => 'S'),
  array('id' => '76','codigo_conta' => '55','classificacao_conta' => '1150100001','nome_conta' => 'MERCADORIAS PARA REVENDA','tipo_conta' => 'A'),
  array('id' => '77','codigo_conta' => '56','classificacao_conta' => '1150100002','nome_conta' => 'MERCADORIA EM CONSIGNAÇÃO','tipo_conta' => 'A'),
  array('id' => '78','codigo_conta' => '59','classificacao_conta' => '1150100003','nome_conta' => 'PRODUTOS ACABADOS','tipo_conta' => 'A'),
  array('id' => '79','codigo_conta' => '60','classificacao_conta' => '1150100004','nome_conta' => 'PRODUTOS EM ELABORAÇÃO','tipo_conta' => 'A'),
  array('id' => '80','codigo_conta' => '64','classificacao_conta' => '11502','nome_conta' => '(-) PROVISÃO PARA AJUSTES DO ESTOQUE','tipo_conta' => 'S'),
  array('id' => '81','codigo_conta' => '65','classificacao_conta' => '116','nome_conta' => 'DESPESAS PAGAS ANTECIPADAMENTE','tipo_conta' => 'S'),
  array('id' => '82','codigo_conta' => '66','classificacao_conta' => '11601','nome_conta' => 'DESPESAS DE MESES SEGUINTES','tipo_conta' => 'S'),
  array('id' => '83','codigo_conta' => '67','classificacao_conta' => '1160100001','nome_conta' => 'PRÊMIOS DE SEGUROS A APROPRIAR','tipo_conta' => 'A'),
  array('id' => '84','codigo_conta' => '68','classificacao_conta' => '1160200002','nome_conta' => 'ASSINATURAS E ANUIDADES','tipo_conta' => 'A'),
  array('id' => '85','codigo_conta' => '501','classificacao_conta' => '12','nome_conta' => 'ATIVO NÃO-CIRCULANTE','tipo_conta' => 'S'),
  array('id' => '86','codigo_conta' => '69','classificacao_conta' => '121','nome_conta' => 'CLIENTES','tipo_conta' => 'S'),
  array('id' => '87','codigo_conta' => '71','classificacao_conta' => '12101','nome_conta' => 'DUPLICATAS A RECEBER','tipo_conta' => 'S'),
  array('id' => '88','codigo_conta' => '72','classificacao_conta' => '1210100001','nome_conta' => 'CLIENTE ','tipo_conta' => 'A'),
  array('id' => '89','codigo_conta' => '74','classificacao_conta' => '1210100002','nome_conta' => '(-) DUPLICATAS DESCONTADAS','tipo_conta' => 'A'),
  array('id' => '90','codigo_conta' => '75','classificacao_conta' => '1210100003','nome_conta' => '(-) CRÉDITOS VENCIDOS E NÃO LIQUIDADOS','tipo_conta' => 'A'),
  array('id' => '91','codigo_conta' => '76','classificacao_conta' => '122','nome_conta' => 'OUTROS CRÉDITOS','tipo_conta' => 'S'),
  array('id' => '92','codigo_conta' => '77','classificacao_conta' => '12201','nome_conta' => 'TÍTULOS A RECEBER','tipo_conta' => 'S'),
  array('id' => '93','codigo_conta' => '78','classificacao_conta' => '12202','nome_conta' => 'BANCOS CONTA VINCULADA','tipo_conta' => 'S'),
  array('id' => '94','codigo_conta' => '79','classificacao_conta' => '12203','nome_conta' => 'CONTROLADORA, CONTROLADAS E COLIGADAS','tipo_conta' => 'S'),
  array('id' => '95','codigo_conta' => '80','classificacao_conta' => '12204','nome_conta' => 'SÓCIOS, ADMINISTRADORES E PESSOAS LIGADA','tipo_conta' => 'S'),
  array('id' => '96','codigo_conta' => '81','classificacao_conta' => '12205','nome_conta' => 'APLICAÇÕES FINANCEIRAS','tipo_conta' => 'S'),
  array('id' => '97','codigo_conta' => '82','classificacao_conta' => '12206','nome_conta' => 'DEPÓSITOS JUDICIAIS','tipo_conta' => 'S'),
  array('id' => '98','codigo_conta' => '511','classificacao_conta' => '1220600001','nome_conta' => 'DEPOSITOS JUDICIAIS','tipo_conta' => 'A'),
  array('id' => '99','codigo_conta' => '83','classificacao_conta' => '12207','nome_conta' => 'EMPRESTIMO L.P','tipo_conta' => 'S'),
  array('id' => '100','codigo_conta' => '85','classificacao_conta' => '1220700001','nome_conta' => 'EMPRESTIMO ','tipo_conta' => 'A'),
  array('id' => '101','codigo_conta' => '84','classificacao_conta' => '12208','nome_conta' => 'TRIBUTOS A RECUPERAR','tipo_conta' => 'S'),
  array('id' => '102','codigo_conta' => '86','classificacao_conta' => '12209','nome_conta' => 'DEPÓSITOS POR INCENTIVOS FISCAIS','tipo_conta' => 'S'),
  array('id' => '103','codigo_conta' => '88','classificacao_conta' => '123','nome_conta' => 'INVESTIMENTOS','tipo_conta' => 'S'),
  array('id' => '104','codigo_conta' => '89','classificacao_conta' => '12301','nome_conta' => 'CONTROLADAS E COLIGADAS - EQUIV. PATRIM.','tipo_conta' => 'S'),
  array('id' => '105','codigo_conta' => '90','classificacao_conta' => '1230100001','nome_conta' => 'INVESTIMENTO EM CONTROLADA ','tipo_conta' => 'A'),
  array('id' => '106','codigo_conta' => '91','classificacao_conta' => '1230100002','nome_conta' => 'INVESTIMENTO EM OUTRAS SOCIEDADES','tipo_conta' => 'A'),
  array('id' => '107','codigo_conta' => '95','classificacao_conta' => '12302','nome_conta' => 'CONTROLADAS E COLIGADAS CUSTO CORRIGIDO','tipo_conta' => 'S'),
  array('id' => '108','codigo_conta' => '96','classificacao_conta' => '12303','nome_conta' => 'OUTRAS PARTICIPAÇÕES SOCIETÁRIAS','tipo_conta' => 'S'),
  array('id' => '109','codigo_conta' => '512','classificacao_conta' => '1230300001','nome_conta' => 'INVESTIMENTO EM SCP','tipo_conta' => 'A'),
  array('id' => '110','codigo_conta' => '97','classificacao_conta' => '12304','nome_conta' => 'PARTICIPAÇÕES POR INCENTIVOS FISCAIS','tipo_conta' => 'S'),
  array('id' => '111','codigo_conta' => '98','classificacao_conta' => '1230400001','nome_conta' => 'FINOR','tipo_conta' => 'A'),
  array('id' => '112','codigo_conta' => '99','classificacao_conta' => '1230400002','nome_conta' => 'FINAM','tipo_conta' => 'A'),
  array('id' => '113','codigo_conta' => '100','classificacao_conta' => '12305','nome_conta' => 'CONSÓRCIOS EM ANDAMENTO','tipo_conta' => 'S'),
  array('id' => '114','codigo_conta' => '102','classificacao_conta' => '1230500001','nome_conta' => 'CONSÓRCIOS','tipo_conta' => 'A'),
  array('id' => '115','codigo_conta' => '682','classificacao_conta' => '1230500002','nome_conta' => 'CONSORCIO 2','tipo_conta' => 'A'),
  array('id' => '116','codigo_conta' => '689','classificacao_conta' => '1230500003','nome_conta' => 'CONSORCIO 3','tipo_conta' => 'A'),
  array('id' => '117','codigo_conta' => '101','classificacao_conta' => '12306','nome_conta' => 'OUTROS INVESTIMENTOS PERMANENTES','tipo_conta' => 'S'),
  array('id' => '118','codigo_conta' => '103','classificacao_conta' => '1230600001','nome_conta' => 'CAUÇÕES PERMANENTES','tipo_conta' => 'A'),
  array('id' => '119','codigo_conta' => '104','classificacao_conta' => '12307','nome_conta' => '(-) PROVISÃO PARA PERDAS PERMANENTE','tipo_conta' => 'S'),
  array('id' => '120','codigo_conta' => '105','classificacao_conta' => '1230700001','nome_conta' => '(-) CONTROLADAS E COLIGADAS EQUI. PATRIM','tipo_conta' => 'A'),
  array('id' => '121','codigo_conta' => '111','classificacao_conta' => '124','nome_conta' => 'IMOBILIZADO','tipo_conta' => 'S'),
  array('id' => '122','codigo_conta' => '112','classificacao_conta' => '12401','nome_conta' => 'IMÓVEIS','tipo_conta' => 'S'),
  array('id' => '123','codigo_conta' => '113','classificacao_conta' => '1240100001','nome_conta' => 'TERRENOS','tipo_conta' => 'A'),
  array('id' => '124','codigo_conta' => '114','classificacao_conta' => '1240100002','nome_conta' => 'EDIFÍCIOS','tipo_conta' => 'A'),
  array('id' => '125','codigo_conta' => '115','classificacao_conta' => '1240100003','nome_conta' => 'CONSTRUÇÕES','tipo_conta' => 'A'),
  array('id' => '126','codigo_conta' => '116','classificacao_conta' => '12402','nome_conta' => 'MÓVEIS E UTENSÍLIOS','tipo_conta' => 'S'),
  array('id' => '127','codigo_conta' => '117','classificacao_conta' => '1240200001','nome_conta' => 'MÓVEIS E UTENSÍLIOS','tipo_conta' => 'A'),
  array('id' => '128','codigo_conta' => '118','classificacao_conta' => '12403','nome_conta' => 'MÁQUINAS, EQUIPAMENTOS E FERRAMENTAS','tipo_conta' => 'S'),
  array('id' => '129','codigo_conta' => '119','classificacao_conta' => '1240300001','nome_conta' => 'MÁQUINAS E EQUIPAMENTOS','tipo_conta' => 'A'),
  array('id' => '130','codigo_conta' => '120','classificacao_conta' => '12404','nome_conta' => 'VEÍCULOS','tipo_conta' => 'S'),
  array('id' => '131','codigo_conta' => '121','classificacao_conta' => '1240400001','nome_conta' => 'VEÍCULOS','tipo_conta' => 'A'),
  array('id' => '132','codigo_conta' => '122','classificacao_conta' => '12405','nome_conta' => 'INSTALAÇÕES','tipo_conta' => 'S'),
  array('id' => '133','codigo_conta' => '513','classificacao_conta' => '1240500001','nome_conta' => 'INSTALAÇÕES','tipo_conta' => 'A'),
  array('id' => '134','codigo_conta' => '124','classificacao_conta' => '12406','nome_conta' => 'COMPUTADORES E PERIFERICOS','tipo_conta' => 'S'),
  array('id' => '135','codigo_conta' => '549','classificacao_conta' => '1240600001','nome_conta' => 'COMPUTADORES E PERIFÉRICOS','tipo_conta' => 'A'),
  array('id' => '136','codigo_conta' => '739','classificacao_conta' => '12407','nome_conta' => 'BENFEITORIA EM IMOVIES DE TERCEIROS','tipo_conta' => 'S'),
  array('id' => '137','codigo_conta' => '740','classificacao_conta' => '1240700001','nome_conta' => 'BENFEITORIA EM IMOVEIS DE TERCEIROS','tipo_conta' => 'A'),
  array('id' => '138','codigo_conta' => '125','classificacao_conta' => '12409','nome_conta' => '(-) DEPRECIAÇÕES, AMORT. E EXAUS. ACUMUL','tipo_conta' => 'S'),
  array('id' => '139','codigo_conta' => '126','classificacao_conta' => '1240900001','nome_conta' => '(-) DEPRECIAÇÕES DE EDIFÍCIOS','tipo_conta' => 'A'),
  array('id' => '140','codigo_conta' => '127','classificacao_conta' => '1240900002','nome_conta' => '(-) DEPRECIAÇÕES DE MÓVEIS E UTENSÍLIOS','tipo_conta' => 'A'),
  array('id' => '141','codigo_conta' => '128','classificacao_conta' => '1240900003','nome_conta' => '(-) DEPRECIAÇÕES DE MÁQUINAS, EQUIP. FER','tipo_conta' => 'A'),
  array('id' => '142','codigo_conta' => '129','classificacao_conta' => '1240900004','nome_conta' => '(-) DEPRECIAÇÕES DE VEÍCULOS','tipo_conta' => 'A'),
  array('id' => '143','codigo_conta' => '130','classificacao_conta' => '1240900005','nome_conta' => '(-) DEPRECIAÇÃO INSTALAÇÕES','tipo_conta' => 'A'),
  array('id' => '144','codigo_conta' => '131','classificacao_conta' => '1240900006','nome_conta' => '(-) DEPRECIAÇÃO DE COMPUTADORES E PERIFÉRICOS','tipo_conta' => 'A'),
  array('id' => '145','codigo_conta' => '741','classificacao_conta' => '1240900007','nome_conta' => '(-) DEPRECIAÇÃO DE BENFEITORIA EM IMOVEIS DE TERCE','tipo_conta' => 'A'),
  array('id' => '146','codigo_conta' => '502','classificacao_conta' => '125','nome_conta' => 'INTANGÍVEL','tipo_conta' => 'S'),
  array('id' => '147','codigo_conta' => '123','classificacao_conta' => '12501','nome_conta' => 'MARCAS, DIREITOS E PATENTES','tipo_conta' => 'S'),
  array('id' => '148','codigo_conta' => '559','classificacao_conta' => '1250100001','nome_conta' => 'SOFTWARES','tipo_conta' => 'A'),
  array('id' => '149','codigo_conta' => '737','classificacao_conta' => '1250100002','nome_conta' => '(-) SOFTWARES','tipo_conta' => 'A'),
  array('id' => '150','codigo_conta' => '149','classificacao_conta' => '2','nome_conta' => 'PASSIVO','tipo_conta' => 'S'),
  array('id' => '151','codigo_conta' => '150','classificacao_conta' => '21','nome_conta' => 'PASSIVO CIRCULANTE','tipo_conta' => 'S'),
  array('id' => '152','codigo_conta' => '382','classificacao_conta' => '211','nome_conta' => 'EMPRÉSTIMOS E FINANCIAMENTOS','tipo_conta' => 'S'),
  array('id' => '153','codigo_conta' => '151','classificacao_conta' => '21101','nome_conta' => 'EMPRÉSTIMOS','tipo_conta' => 'S'),
  array('id' => '154','codigo_conta' => '152','classificacao_conta' => '2110100001','nome_conta' => 'EMPRESTIMO 1 ','tipo_conta' => 'A'),
  array('id' => '155','codigo_conta' => '567','classificacao_conta' => '2110100002','nome_conta' => '(-) JUROS A INCORRER','tipo_conta' => 'A'),
  array('id' => '156','codigo_conta' => '153','classificacao_conta' => '21102','nome_conta' => 'EMPRÉSTIMOS ESTRANGEIROS','tipo_conta' => 'S'),
  array('id' => '157','codigo_conta' => '157','classificacao_conta' => '21105','nome_conta' => 'TÍTULOS A PAGAR','tipo_conta' => 'S'),
  array('id' => '158','codigo_conta' => '158','classificacao_conta' => '21106','nome_conta' => 'ADIANTAMENTOS SOBRE CONTRATOS DE CÂMBIO','tipo_conta' => 'S'),
  array('id' => '159','codigo_conta' => '515','classificacao_conta' => '2110600001','nome_conta' => 'ADIANTAMENTO DE CAMBIO','tipo_conta' => 'A'),
  array('id' => '160','codigo_conta' => '159','classificacao_conta' => '21107','nome_conta' => 'CONTROLADORA, CONTROLADAS E COLIGADAS','tipo_conta' => 'S'),
  array('id' => '161','codigo_conta' => '160','classificacao_conta' => '212','nome_conta' => 'DEBÊNTURES','tipo_conta' => 'S'),
  array('id' => '162','codigo_conta' => '161','classificacao_conta' => '21201','nome_conta' => 'DEBÊNTURES CONVERSÍVEIS EM AÇÕES','tipo_conta' => 'S'),
  array('id' => '163','codigo_conta' => '162','classificacao_conta' => '21202','nome_conta' => 'DEBÊNTURES NÃO CONVERSÍVEIS','tipo_conta' => 'S'),
  array('id' => '164','codigo_conta' => '163','classificacao_conta' => '21203','nome_conta' => '(-) DESÁGIO A APROPRIAR','tipo_conta' => 'S'),
  array('id' => '165','codigo_conta' => '164','classificacao_conta' => '213','nome_conta' => 'FORNECEDORES','tipo_conta' => 'S'),
  array('id' => '166','codigo_conta' => '165','classificacao_conta' => '21301','nome_conta' => 'FORNECEDORES','tipo_conta' => 'S'),
  array('id' => '167','codigo_conta' => '166','classificacao_conta' => '2130100001','nome_conta' => 'FORNECEDORES DIVERSOS','tipo_conta' => 'A'),
  array('id' => '168','codigo_conta' => '757','classificacao_conta' => '2130100002','nome_conta' => 'CIA BRASILEIRA DE DISTRIBUICAO','tipo_conta' => 'A'),
  array('id' => '169','codigo_conta' => '758','classificacao_conta' => '2130100003','nome_conta' => 'CERTISIGN CERTIFICADORA DIGITAL S.A','tipo_conta' => 'A'),
  array('id' => '170','codigo_conta' => '759','classificacao_conta' => '2130100004','nome_conta' => 'AMAZON AWS SERVICOS BRASIL LTDA','tipo_conta' => 'A'),
  array('id' => '171','codigo_conta' => '760','classificacao_conta' => '2130100005','nome_conta' => 'VONO TELECOM LTDA','tipo_conta' => 'A'),
  array('id' => '172','codigo_conta' => '761','classificacao_conta' => '2130100006','nome_conta' => 'DILETEC PROCESSAMENTO DE DADOS E SOFTWARE EIRELI','tipo_conta' => 'A'),
  array('id' => '173','codigo_conta' => '168','classificacao_conta' => '21302','nome_conta' => 'FORNECEDORES ESTRANGEIROS','tipo_conta' => 'S'),
  array('id' => '174','codigo_conta' => '514','classificacao_conta' => '2130200001','nome_conta' => 'FORNECEDORES DE IMPORTAÇÃO ','tipo_conta' => 'A'),
  array('id' => '175','codigo_conta' => '169','classificacao_conta' => '214','nome_conta' => 'OBRIGAÇÕES TRIBUTÁRIAS','tipo_conta' => 'S'),
  array('id' => '176','codigo_conta' => '170','classificacao_conta' => '21401','nome_conta' => 'IMPOSTOS E CONTRIBUIÇÕES A RECOLHER','tipo_conta' => 'S'),
  array('id' => '177','codigo_conta' => '171','classificacao_conta' => '2140100001','nome_conta' => 'IRRF S/ SALARIOS','tipo_conta' => 'A'),
  array('id' => '178','codigo_conta' => '172','classificacao_conta' => '2140100002','nome_conta' => 'ICMS A RECOLHER','tipo_conta' => 'A'),
  array('id' => '179','codigo_conta' => '173','classificacao_conta' => '2140100003','nome_conta' => 'ISS A RECOLHER','tipo_conta' => 'A'),
  array('id' => '180','codigo_conta' => '176','classificacao_conta' => '2140100004','nome_conta' => 'IMPOSTO DE RENDA A RECOLHER','tipo_conta' => 'A'),
  array('id' => '181','codigo_conta' => '177','classificacao_conta' => '2140100005','nome_conta' => 'CONTRIBUIÇÃO SOCIAL A RECOLHER','tipo_conta' => 'A'),
  array('id' => '182','codigo_conta' => '178','classificacao_conta' => '2140100006','nome_conta' => 'IRRF A RECOLHER','tipo_conta' => 'A'),
  array('id' => '183','codigo_conta' => '179','classificacao_conta' => '2140100007','nome_conta' => 'PIS A RECOLHER','tipo_conta' => 'A'),
  array('id' => '184','codigo_conta' => '180','classificacao_conta' => '2140100008','nome_conta' => 'COFINS A RECOLHER','tipo_conta' => 'A'),
  array('id' => '185','codigo_conta' => '181','classificacao_conta' => '2140100009','nome_conta' => 'PROVISÃO PARA IOF','tipo_conta' => 'A'),
  array('id' => '186','codigo_conta' => '183','classificacao_conta' => '2140100010','nome_conta' => 'ISS RETIDO A RECOLHER','tipo_conta' => 'A'),
  array('id' => '187','codigo_conta' => '184','classificacao_conta' => '2140100011','nome_conta' => 'INSS RETIDO A RECOLHER','tipo_conta' => 'A'),
  array('id' => '188','codigo_conta' => '479','classificacao_conta' => '2140100012','nome_conta' => 'SIMPLES A RECOLHER','tipo_conta' => 'A'),
  array('id' => '189','codigo_conta' => '481','classificacao_conta' => '2140100013','nome_conta' => 'IMPOSTOS RETIDOS LEI 10.833 A RECOLHER','tipo_conta' => 'A'),
  array('id' => '190','codigo_conta' => '483','classificacao_conta' => '2140100014','nome_conta' => 'REFIS A RECOLHER','tipo_conta' => 'A'),
  array('id' => '191','codigo_conta' => '487','classificacao_conta' => '2140100015','nome_conta' => 'PIS RETIDO A RECOLHER','tipo_conta' => 'A'),
  array('id' => '192','codigo_conta' => '488','classificacao_conta' => '2140100016','nome_conta' => 'COFINS RETIDO A RECOLHER','tipo_conta' => 'A'),
  array('id' => '193','codigo_conta' => '489','classificacao_conta' => '2140100017','nome_conta' => 'CONTRIBUIÇÃO SOCIAL RETIDA A RECOLHER','tipo_conta' => 'A'),
  array('id' => '194','codigo_conta' => '491','classificacao_conta' => '2140100018','nome_conta' => 'CONTRIBUIÇÃO SINDICAL A RECOLHER','tipo_conta' => 'A'),
  array('id' => '195','codigo_conta' => '556','classificacao_conta' => '2140100019','nome_conta' => 'PARCELAMENTO IMPOSTOS','tipo_conta' => 'A'),
  array('id' => '196','codigo_conta' => '185','classificacao_conta' => '215','nome_conta' => 'OBRIGAÇÕES TRABALHISTA E PREVIDENCIÁRIA','tipo_conta' => 'S'),
  array('id' => '197','codigo_conta' => '186','classificacao_conta' => '21501','nome_conta' => 'OBRIGAÇÕES COM O PESSOAL','tipo_conta' => 'S'),
  array('id' => '198','codigo_conta' => '187','classificacao_conta' => '2147483647','nome_conta' => 'SALÁRIOS E ORDENADOS A PAGAR','tipo_conta' => 'A'),
  array('id' => '199','codigo_conta' => '188','classificacao_conta' => '2147483647','nome_conta' => 'PRÓ-LABORE A PAGAR','tipo_conta' => 'A'),
  array('id' => '200','codigo_conta' => '189','classificacao_conta' => '2147483647','nome_conta' => 'GRATIFICAÇÕES A PAGAR','tipo_conta' => 'A'),
  array('id' => '201','codigo_conta' => '516','classificacao_conta' => '2147483647','nome_conta' => 'FERIAS A PAGAR','tipo_conta' => 'A'),
  array('id' => '202','codigo_conta' => '517','classificacao_conta' => '2147483647','nome_conta' => '13º SALARIO A PAGAR','tipo_conta' => 'A'),
  array('id' => '203','codigo_conta' => '518','classificacao_conta' => '2147483647','nome_conta' => 'RESCISÕES A PAGAR','tipo_conta' => 'A'),
  array('id' => '204','codigo_conta' => '190','classificacao_conta' => '21502','nome_conta' => 'OBRIGAÇÕES SOCIAIS','tipo_conta' => 'S'),
  array('id' => '205','codigo_conta' => '191','classificacao_conta' => '2147483647','nome_conta' => 'INSS A RECOLHER','tipo_conta' => 'A'),
  array('id' => '206','codigo_conta' => '192','classificacao_conta' => '2147483647','nome_conta' => 'FGTS A RECOLHER','tipo_conta' => 'A'),
  array('id' => '207','codigo_conta' => '494','classificacao_conta' => '2147483647','nome_conta' => 'PIS S/ FOLHA A RECOLHER','tipo_conta' => 'A'),
  array('id' => '208','codigo_conta' => '519','classificacao_conta' => '2147483647','nome_conta' => 'CONTRIBUIÇÃO ASSISTENCIAL ','tipo_conta' => 'A'),
  array('id' => '209','codigo_conta' => '520','classificacao_conta' => '2147483647','nome_conta' => 'CONTRIBUICAO SINDICAL','tipo_conta' => 'A'),
  array('id' => '210','codigo_conta' => '193','classificacao_conta' => '21503','nome_conta' => 'PROVISÕES','tipo_conta' => 'S'),
  array('id' => '211','codigo_conta' => '194','classificacao_conta' => '2147483647','nome_conta' => 'PROVISÕES PARA FÉRIAS','tipo_conta' => 'A'),
  array('id' => '212','codigo_conta' => '195','classificacao_conta' => '2147483647','nome_conta' => 'PROVISÕES PARA 13º SALÁRIO','tipo_conta' => 'A'),
  array('id' => '213','codigo_conta' => '196','classificacao_conta' => '2147483647','nome_conta' => 'INSS SOBRE PROVISÕES PARA FÉRIAS','tipo_conta' => 'A'),
  array('id' => '214','codigo_conta' => '197','classificacao_conta' => '2147483647','nome_conta' => 'INSS SOBRE PROVISÕES PARA 13º SALÁRIO','tipo_conta' => 'A'),
  array('id' => '215','codigo_conta' => '198','classificacao_conta' => '2147483647','nome_conta' => 'FGTS SOBRE PROVISÕES PARA FÉRIAS','tipo_conta' => 'A'),
  array('id' => '216','codigo_conta' => '199','classificacao_conta' => '2147483647','nome_conta' => 'FGTS SOBRE PROVISÕES PARA 13º SALÁRIO','tipo_conta' => 'A'),
  array('id' => '217','codigo_conta' => '495','classificacao_conta' => '2147483647','nome_conta' => 'PIS SOBRE PROVISÕES PARA FÉRIAS','tipo_conta' => 'A'),
  array('id' => '218','codigo_conta' => '496','classificacao_conta' => '2147483647','nome_conta' => 'PIS SOBRE PROVISÕES PARA 13º SALÁRIO','tipo_conta' => 'A'),
  array('id' => '219','codigo_conta' => '200','classificacao_conta' => '216','nome_conta' => 'OUTRAS OBRIGAÇÕES','tipo_conta' => 'S'),
  array('id' => '220','codigo_conta' => '201','classificacao_conta' => '21601','nome_conta' => 'ADIANTAMENTO DE CLIENTES','tipo_conta' => 'S'),
  array('id' => '221','codigo_conta' => '521','classificacao_conta' => '2147483647','nome_conta' => 'ADIANTAMENTO DE CLIENTES','tipo_conta' => 'A'),
  array('id' => '222','codigo_conta' => '202','classificacao_conta' => '21602','nome_conta' => 'DUPLICATAS DESCONTADAS','tipo_conta' => 'S'),
  array('id' => '223','codigo_conta' => '522','classificacao_conta' => '2147483647','nome_conta' => 'DUPLICATAS DESCONTADAS','tipo_conta' => 'A'),
  array('id' => '224','codigo_conta' => '572','classificacao_conta' => '21603','nome_conta' => 'MERCADORIAS EM CONSIGNAÇÃO','tipo_conta' => 'S'),
  array('id' => '225','codigo_conta' => '561','classificacao_conta' => '2147483647','nome_conta' => 'MERCADORIA EM CONSIGNAÇÃO','tipo_conta' => 'A'),
  array('id' => '226','codigo_conta' => '207','classificacao_conta' => '217','nome_conta' => 'DIVIDENDOS, PART. E JURO SOBRE O CAPITAL','tipo_conta' => 'S'),
  array('id' => '227','codigo_conta' => '208','classificacao_conta' => '21701','nome_conta' => 'DIVIDENDOS','tipo_conta' => 'S'),
  array('id' => '228','codigo_conta' => '209','classificacao_conta' => '2147483647','nome_conta' => 'DIVIDENDOS PROPOSTOS','tipo_conta' => 'A'),
  array('id' => '229','codigo_conta' => '210','classificacao_conta' => '2147483647','nome_conta' => 'DIVIDENDOS A PAGAR','tipo_conta' => 'A'),
  array('id' => '230','codigo_conta' => '211','classificacao_conta' => '21702','nome_conta' => 'PARTICIPAÇÕES','tipo_conta' => 'S'),
  array('id' => '231','codigo_conta' => '212','classificacao_conta' => '2147483647','nome_conta' => 'PARTICIPAÇÕES PROPOSTA A ADMINISTRADORES','tipo_conta' => 'A'),
  array('id' => '232','codigo_conta' => '213','classificacao_conta' => '2147483647','nome_conta' => 'PARTICIPAÇÕES PROPOSTA A EMPREGADOS','tipo_conta' => 'A'),
  array('id' => '233','codigo_conta' => '214','classificacao_conta' => '2147483647','nome_conta' => 'PARTICIPAÇÕES A PAGAR','tipo_conta' => 'A'),
  array('id' => '234','codigo_conta' => '215','classificacao_conta' => '21703','nome_conta' => 'JUROS SOBRE CAPITAL PRÓPRIO','tipo_conta' => 'S'),
  array('id' => '235','codigo_conta' => '216','classificacao_conta' => '2147483647','nome_conta' => 'JUROS SOBRE CAPITAL PRÓPRIO A PAGAR','tipo_conta' => 'A'),
  array('id' => '236','codigo_conta' => '503','classificacao_conta' => '22','nome_conta' => 'PASSIVO NÃO-CIRCULANTE','tipo_conta' => 'S'),
  array('id' => '237','codigo_conta' => '217','classificacao_conta' => '221','nome_conta' => 'EMPRÉSTIMOS E FINANCIAMENTOS','tipo_conta' => 'S'),
  array('id' => '238','codigo_conta' => '218','classificacao_conta' => '22101','nome_conta' => 'EMPRÉSTIMOS / MÚTUO','tipo_conta' => 'S'),
  array('id' => '239','codigo_conta' => '219','classificacao_conta' => '2147483647','nome_conta' => 'EMPRÉSTIMOS','tipo_conta' => 'A'),
  array('id' => '240','codigo_conta' => '591','classificacao_conta' => '2147483647','nome_conta' => '(-) JUROS A INCORRER','tipo_conta' => 'A'),
  array('id' => '241','codigo_conta' => '220','classificacao_conta' => '22102','nome_conta' => 'OPERAÇÕES COM COLIGADAS E SÓCIOS','tipo_conta' => 'S'),
  array('id' => '242','codigo_conta' => '578','classificacao_conta' => '2147483647','nome_conta' => 'ADIANTAMENTOS SÓCIOS P/AUMENTO CAPITAL','tipo_conta' => 'A'),
  array('id' => '243','codigo_conta' => '221','classificacao_conta' => '22103','nome_conta' => 'FINANCIAMENTOS','tipo_conta' => 'S'),
  array('id' => '244','codigo_conta' => '222','classificacao_conta' => '2147483647','nome_conta' => 'BANCO ','tipo_conta' => 'A'),
  array('id' => '245','codigo_conta' => '523','classificacao_conta' => '22104','nome_conta' => 'PARCELAMENTO DE IMPOSTOS','tipo_conta' => 'S'),
  array('id' => '246','codigo_conta' => '227','classificacao_conta' => '222','nome_conta' => 'FORNECEDORES','tipo_conta' => 'S'),
  array('id' => '247','codigo_conta' => '228','classificacao_conta' => '22201','nome_conta' => 'FORNECEDORES','tipo_conta' => 'S'),
  array('id' => '248','codigo_conta' => '229','classificacao_conta' => '2147483647','nome_conta' => 'FORNECEDOR ','tipo_conta' => 'A'),
  array('id' => '249','codigo_conta' => '232','classificacao_conta' => '223','nome_conta' => 'OBRIGAÇÕES TRIBUTÁRIAS','tipo_conta' => 'S'),
  array('id' => '250','codigo_conta' => '233','classificacao_conta' => '22301','nome_conta' => 'IMPOSTOS E CONTRIBUIÇÕES A RECOLHER','tipo_conta' => 'S'),
  array('id' => '251','codigo_conta' => '234','classificacao_conta' => '2147483647','nome_conta' => 'PROVISÃO PARA IR SOBRE LUCROS DIFERIDOS','tipo_conta' => 'A'),
  array('id' => '252','codigo_conta' => '242','classificacao_conta' => '23','nome_conta' => 'PATRIMÔNIO LÍQUIDO','tipo_conta' => 'S'),
  array('id' => '253','codigo_conta' => '243','classificacao_conta' => '231','nome_conta' => 'CAPITAL SOCIAL','tipo_conta' => 'S'),
  array('id' => '254','codigo_conta' => '244','classificacao_conta' => '23101','nome_conta' => 'CAPITAL SUBSCRITO','tipo_conta' => 'S'),
  array('id' => '255','codigo_conta' => '245','classificacao_conta' => '2147483647','nome_conta' => 'CAPITAL SOCIAL','tipo_conta' => 'A'),
  array('id' => '256','codigo_conta' => '246','classificacao_conta' => '23102','nome_conta' => '(-) CAPITAL A INTEGRALIZAR','tipo_conta' => 'S'),
  array('id' => '257','codigo_conta' => '247','classificacao_conta' => '2147483647','nome_conta' => 'CAPITAL A INTEGRALIZAR','tipo_conta' => 'A'),
  array('id' => '258','codigo_conta' => '247','classificacao_conta' => '2147483647','nome_conta' => 'CAPITAL A INTEGRALIZAR','tipo_conta' => 'A'),
  array('id' => '259','codigo_conta' => '248','classificacao_conta' => '232','nome_conta' => 'RESERVAS','tipo_conta' => 'S'),
  array('id' => '260','codigo_conta' => '249','classificacao_conta' => '23201','nome_conta' => 'RESERVAS DE CAPITAL','tipo_conta' => 'S'),
  array('id' => '261','codigo_conta' => '250','classificacao_conta' => '2147483647','nome_conta' => 'RESERVAS DE REAVALIAÇÃO','tipo_conta' => 'A'),
  array('id' => '262','codigo_conta' => '257','classificacao_conta' => '23202','nome_conta' => 'RESERVAS DE LUCROS','tipo_conta' => 'S'),
  array('id' => '263','codigo_conta' => '258','classificacao_conta' => '2147483647','nome_conta' => 'RESERVA LEGAL','tipo_conta' => 'A'),
  array('id' => '264','codigo_conta' => '259','classificacao_conta' => '2147483647','nome_conta' => 'RESERVA ESTATUTÁRIA','tipo_conta' => 'A'),
  array('id' => '265','codigo_conta' => '260','classificacao_conta' => '2147483647','nome_conta' => 'RESERVA PARA CONTINGÊNCIAS','tipo_conta' => 'A'),
  array('id' => '266','codigo_conta' => '261','classificacao_conta' => '2147483647','nome_conta' => 'RESERVA DE LUCROS A REALIZAR','tipo_conta' => 'A'),
  array('id' => '267','codigo_conta' => '262','classificacao_conta' => '2147483647','nome_conta' => 'RESERVA ESPECIAL','tipo_conta' => 'A'),
  array('id' => '268','codigo_conta' => '263','classificacao_conta' => '2147483647','nome_conta' => '(-) AÇÕES/QUOTAS EM TESOURARIA','tipo_conta' => 'A'),
  array('id' => '269','codigo_conta' => '264','classificacao_conta' => '233','nome_conta' => 'LUCROS OU PREJUÍZOS ACUMULADOS','tipo_conta' => 'S'),
  array('id' => '270','codigo_conta' => '265','classificacao_conta' => '23301','nome_conta' => 'LUCROS OU PREJUÍZOS ACUMULADOS','tipo_conta' => 'S'),
  array('id' => '271','codigo_conta' => '266','classificacao_conta' => '2147483647','nome_conta' => 'RESERVA DE LUCROS ','tipo_conta' => 'A'),
  array('id' => '272','codigo_conta' => '267','classificacao_conta' => '2147483647','nome_conta' => '(-) PREJUÍZOS ACUMULADOS','tipo_conta' => 'A'),
  array('id' => '273','codigo_conta' => '268','classificacao_conta' => '2147483647','nome_conta' => 'RESULTADO DO EXERCÍCIO EM CURSO','tipo_conta' => 'A'),
  array('id' => '274','codigo_conta' => '601','classificacao_conta' => '2147483647','nome_conta' => 'LUCROS DISTRIBUIDOS','tipo_conta' => 'A'),
  array('id' => '275','codigo_conta' => '646','classificacao_conta' => '2147483647','nome_conta' => 'AJUSTES EXERCICIOS ANTERIORES','tipo_conta' => 'A'),
  array('id' => '276','codigo_conta' => '269','classificacao_conta' => '3','nome_conta' => 'CONTAS DE RESULTADOS - CUSTOS E DESPESAS','tipo_conta' => 'S'),
  array('id' => '277','codigo_conta' => '500','classificacao_conta' => '31','nome_conta' => 'CUSTOS','tipo_conta' => 'S'),
  array('id' => '278','codigo_conta' => '270','classificacao_conta' => '311','nome_conta' => 'CUSTOS DIRETOS DE PRODUÇÃO','tipo_conta' => 'S'),
  array('id' => '279','codigo_conta' => '271','classificacao_conta' => '31101','nome_conta' => 'CUSTO DE COMERCIALIZAÇÃO','tipo_conta' => 'S'),
  array('id' => '280','codigo_conta' => '272','classificacao_conta' => '2147483647','nome_conta' => 'MATERIAL APLICADO','tipo_conta' => 'A'),
  array('id' => '281','codigo_conta' => '524','classificacao_conta' => '2147483647','nome_conta' => 'MERCADORIAS P/REVENDA','tipo_conta' => 'A'),
  array('id' => '282','codigo_conta' => '525','classificacao_conta' => '2147483647','nome_conta' => 'FRETES S/COMPRAS','tipo_conta' => 'A'),
  array('id' => '283','codigo_conta' => '526','classificacao_conta' => '2147483647','nome_conta' => 'DEVOLUÇAO DE MERCADORIA ','tipo_conta' => 'A'),
  array('id' => '284','codigo_conta' => '527','classificacao_conta' => '2147483647','nome_conta' => 'ICMS S/COMPRA','tipo_conta' => 'A'),
  array('id' => '285','codigo_conta' => '528','classificacao_conta' => '2147483647','nome_conta' => 'TRANSFERENCIA P/CONSUMO','tipo_conta' => 'A'),
  array('id' => '286','codigo_conta' => '273','classificacao_conta' => '31102','nome_conta' => 'MÃO-DE-OBRA DIRETA','tipo_conta' => 'S'),
  array('id' => '287','codigo_conta' => '274','classificacao_conta' => '2147483647','nome_conta' => 'SALÁRIOS E ORDENADOS','tipo_conta' => 'A'),
  array('id' => '288','codigo_conta' => '275','classificacao_conta' => '2147483647','nome_conta' => 'PRÓ-LABORE','tipo_conta' => 'A'),
  array('id' => '289','codigo_conta' => '276','classificacao_conta' => '2147483647','nome_conta' => 'PRÊMIOS DE GRATIFICAÇÕES','tipo_conta' => 'A'),
  array('id' => '290','codigo_conta' => '277','classificacao_conta' => '2147483647','nome_conta' => '13º SALÁRIO','tipo_conta' => 'A'),
  array('id' => '291','codigo_conta' => '278','classificacao_conta' => '2147483647','nome_conta' => 'FÉRIAS','tipo_conta' => 'A'),
  array('id' => '292','codigo_conta' => '279','classificacao_conta' => '2147483647','nome_conta' => 'INSS','tipo_conta' => 'A'),
  array('id' => '293','codigo_conta' => '280','classificacao_conta' => '2147483647','nome_conta' => 'FGTS','tipo_conta' => 'A'),
  array('id' => '294','codigo_conta' => '281','classificacao_conta' => '2147483647','nome_conta' => 'INDENIZAÇÕES E AVISO PRÉVIO','tipo_conta' => 'A'),
  array('id' => '295','codigo_conta' => '282','classificacao_conta' => '2147483647','nome_conta' => 'ASSISTÊNCIA MÉDICA E SOCIAL','tipo_conta' => 'A'),
  array('id' => '296','codigo_conta' => '585','classificacao_conta' => '31103','nome_conta' => 'CUSTOS COM IMPORTAÇÃO','tipo_conta' => 'S'),
  array('id' => '297','codigo_conta' => '586','classificacao_conta' => '2147483647','nome_conta' => 'TAXA / IMPOSTOS IMPORTAÇÃO ','tipo_conta' => 'A'),
  array('id' => '298','codigo_conta' => '604','classificacao_conta' => '2147483647','nome_conta' => 'OUTRAS DESPESAS C/IMPORTAÇÃO','tipo_conta' => 'A'),
  array('id' => '299','codigo_conta' => '608','classificacao_conta' => '2147483647','nome_conta' => 'FRETES E CARRETOS ','tipo_conta' => 'A'),
  array('id' => '300','codigo_conta' => '609','classificacao_conta' => '2147483647','nome_conta' => 'ARMAZENAGEM E CAPATAZIA ','tipo_conta' => 'A'),
  array('id' => '301','codigo_conta' => '610','classificacao_conta' => '2147483647','nome_conta' => 'SERVIÇOS PRESTADOS PJ ','tipo_conta' => 'A'),
  array('id' => '302','codigo_conta' => '611','classificacao_conta' => '2147483647','nome_conta' => 'VARIAÇÃO CAMBIAL','tipo_conta' => 'A'),
  array('id' => '303','codigo_conta' => '616','classificacao_conta' => '2147483647','nome_conta' => 'SEGURO INTERNACIONAL','tipo_conta' => 'A'),
  array('id' => '304','codigo_conta' => '617','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS ADUANEIRAS ','tipo_conta' => 'A'),
  array('id' => '305','codigo_conta' => '618','classificacao_conta' => '2147483647','nome_conta' => 'IMPOSTO DE IMPORTAÇÃO ','tipo_conta' => 'A'),
  array('id' => '306','codigo_conta' => '619','classificacao_conta' => '2147483647','nome_conta' => 'COFINS ','tipo_conta' => 'A'),
  array('id' => '307','codigo_conta' => '620','classificacao_conta' => '2147483647','nome_conta' => 'ICMS S/IMPORTAÇÃO ','tipo_conta' => 'A'),
  array('id' => '308','codigo_conta' => '643','classificacao_conta' => '2147483647','nome_conta' => 'PIS','tipo_conta' => 'A'),
  array('id' => '309','codigo_conta' => '654','classificacao_conta' => '2147483647','nome_conta' => 'IPI S/IMPORTAÇÃO','tipo_conta' => 'A'),
  array('id' => '310','codigo_conta' => '283','classificacao_conta' => '312','nome_conta' => 'CUSTO DE SERVICOS','tipo_conta' => 'S'),
  array('id' => '311','codigo_conta' => '284','classificacao_conta' => '31201','nome_conta' => 'SERVICOS CONTRATADOS','tipo_conta' => 'S'),
  array('id' => '312','codigo_conta' => '529','classificacao_conta' => '2147483647','nome_conta' => 'ALUGUEL DE EQUIPAMENTOS','tipo_conta' => 'A'),
  array('id' => '313','codigo_conta' => '530','classificacao_conta' => '2147483647','nome_conta' => 'CONSERVAÇÃO DE EQUIPAMENTOS','tipo_conta' => 'A'),
  array('id' => '314','codigo_conta' => '531','classificacao_conta' => '2147483647','nome_conta' => 'MATERIAL DE CONSUMO','tipo_conta' => 'A'),
  array('id' => '315','codigo_conta' => '532','classificacao_conta' => '2147483647','nome_conta' => 'PEQUENAS FERRAMENTAS','tipo_conta' => 'A'),
  array('id' => '316','codigo_conta' => '533','classificacao_conta' => '2147483647','nome_conta' => 'SERVIÇOS PRESTADOS - PJ','tipo_conta' => 'A'),
  array('id' => '317','codigo_conta' => '534','classificacao_conta' => '2147483647','nome_conta' => 'SERVIÇOS PRESTADOS - PF','tipo_conta' => 'A'),
  array('id' => '318','codigo_conta' => '535','classificacao_conta' => '2147483647','nome_conta' => 'DEPRECIAÇÃO ','tipo_conta' => 'A'),
  array('id' => '319','codigo_conta' => '288','classificacao_conta' => '31205','nome_conta' => 'ALUGUEIS E ARRENDAMENTOS','tipo_conta' => 'S'),
  array('id' => '320','codigo_conta' => '536','classificacao_conta' => '2147483647','nome_conta' => 'ALUGUEIS - CUSTO','tipo_conta' => 'A'),
  array('id' => '321','codigo_conta' => '295','classificacao_conta' => '32','nome_conta' => 'DESPESAS OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '322','codigo_conta' => '296','classificacao_conta' => '321','nome_conta' => 'DESPESAS COM SALARIOS E ENCARGOS','tipo_conta' => 'S'),
  array('id' => '323','codigo_conta' => '297','classificacao_conta' => '32101','nome_conta' => 'DESPESAS COM PESSOAL','tipo_conta' => 'S'),
  array('id' => '324','codigo_conta' => '298','classificacao_conta' => '2147483647','nome_conta' => 'SALÁRIOS E ORDENADOS','tipo_conta' => 'A'),
  array('id' => '325','codigo_conta' => '299','classificacao_conta' => '2147483647','nome_conta' => 'PRÓ-LABORE','tipo_conta' => 'A'),
  array('id' => '326','codigo_conta' => '300','classificacao_conta' => '2147483647','nome_conta' => 'PRÊMIOS E GRATIFICAÇÕES','tipo_conta' => 'A'),
  array('id' => '327','codigo_conta' => '301','classificacao_conta' => '2147483647','nome_conta' => '13º SALÁRIO','tipo_conta' => 'A'),
  array('id' => '328','codigo_conta' => '302','classificacao_conta' => '2147483647','nome_conta' => 'FÉRIAS','tipo_conta' => 'A'),
  array('id' => '329','codigo_conta' => '303','classificacao_conta' => '2147483647','nome_conta' => 'INSS','tipo_conta' => 'A'),
  array('id' => '330','codigo_conta' => '304','classificacao_conta' => '2147483647','nome_conta' => 'FGTS','tipo_conta' => 'A'),
  array('id' => '331','codigo_conta' => '305','classificacao_conta' => '2147483647','nome_conta' => 'INDENIZAÇÕES E AVISO PRÉVIO','tipo_conta' => 'A'),
  array('id' => '332','codigo_conta' => '306','classificacao_conta' => '2147483647','nome_conta' => 'ASSISTÊNCIA MÉDICA / ODONTOLÓGICA','tipo_conta' => 'A'),
  array('id' => '333','codigo_conta' => '498','classificacao_conta' => '2147483647','nome_conta' => 'VALE REFEIÇÃO','tipo_conta' => 'A'),
  array('id' => '334','codigo_conta' => '537','classificacao_conta' => '2147483647','nome_conta' => 'VALE TRANSPORTE','tipo_conta' => 'A'),
  array('id' => '335','codigo_conta' => '562','classificacao_conta' => '2147483647','nome_conta' => 'CURSOS/TREINAMENTOS E CONGRESSOS','tipo_conta' => 'A'),
  array('id' => '336','codigo_conta' => '600','classificacao_conta' => '2147483647','nome_conta' => 'COMISSÕES','tipo_conta' => 'A'),
  array('id' => '337','codigo_conta' => '630','classificacao_conta' => '2147483647','nome_conta' => 'UNIFORMES ','tipo_conta' => 'A'),
  array('id' => '338','codigo_conta' => '327','classificacao_conta' => '322','nome_conta' => 'DESPESAS ADMINISTRATIVAS','tipo_conta' => 'S'),
  array('id' => '339','codigo_conta' => '353','classificacao_conta' => '32201','nome_conta' => 'DESPESAS GERAIS','tipo_conta' => 'S'),
  array('id' => '340','codigo_conta' => '354','classificacao_conta' => '2147483647','nome_conta' => 'ENERGIA ELÉTRICA','tipo_conta' => 'A'),
  array('id' => '341','codigo_conta' => '355','classificacao_conta' => '2147483647','nome_conta' => 'ÁGUA E ESGOTO','tipo_conta' => 'A'),
  array('id' => '342','codigo_conta' => '356','classificacao_conta' => '2147483647','nome_conta' => 'TELEFONE','tipo_conta' => 'A'),
  array('id' => '343','codigo_conta' => '357','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS POSTAIS CORREIOS','tipo_conta' => 'A'),
  array('id' => '344','codigo_conta' => '358','classificacao_conta' => '2147483647','nome_conta' => 'SEGUROS','tipo_conta' => 'A'),
  array('id' => '345','codigo_conta' => '359','classificacao_conta' => '2147483647','nome_conta' => 'MATERIAL DE ESCRITÓRIO / EXPEDIENTE','tipo_conta' => 'A'),
  array('id' => '346','codigo_conta' => '360','classificacao_conta' => '2147483647','nome_conta' => 'MATERIAL DE HIGIENE LIMPEZA/ USO E CONSUMO','tipo_conta' => 'A'),
  array('id' => '347','codigo_conta' => '361','classificacao_conta' => '2147483647','nome_conta' => 'HONORARIOS CONTÁBIL','tipo_conta' => 'A'),
  array('id' => '348','codigo_conta' => '362','classificacao_conta' => '2147483647','nome_conta' => 'SERVIÇOS PRESTADOS PESSOA JURIDICA','tipo_conta' => 'A'),
  array('id' => '349','codigo_conta' => '363','classificacao_conta' => '2147483647','nome_conta' => 'DEPRECIAÇÕES E AMORTIZAÇÕES','tipo_conta' => 'A'),
  array('id' => '350','codigo_conta' => '364','classificacao_conta' => '2147483647','nome_conta' => 'COPIAS E ENCADERNACOES','tipo_conta' => 'A'),
  array('id' => '351','codigo_conta' => '365','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS TAXAS JUDICIAIS','tipo_conta' => 'A'),
  array('id' => '352','codigo_conta' => '366','classificacao_conta' => '2147483647','nome_conta' => 'LIVROS, JORNAIS E REVISTAS','tipo_conta' => 'A'),
  array('id' => '353','codigo_conta' => '493','classificacao_conta' => '2147483647','nome_conta' => 'MULTA DE TRÂNSITO','tipo_conta' => 'A'),
  array('id' => '354','codigo_conta' => '538','classificacao_conta' => '2147483647','nome_conta' => 'SERVICOS PRESTADOS P.FISICA','tipo_conta' => 'A'),
  array('id' => '355','codigo_conta' => '539','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM LANCHES E REFEIÇOES','tipo_conta' => 'A'),
  array('id' => '356','codigo_conta' => '540','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM MANUTENÇÃO EQUIPAMENTOS','tipo_conta' => 'A'),
  array('id' => '357','codigo_conta' => '541','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM ESTACIONAMENTO E PEDÁGIOS','tipo_conta' => 'A'),
  array('id' => '358','codigo_conta' => '542','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM CONSERVAÇÃO E MANUTENÇÃO','tipo_conta' => 'A'),
  array('id' => '359','codigo_conta' => '543','classificacao_conta' => '2147483647','nome_conta' => 'BENS DE PEQUENO VALOR','tipo_conta' => 'A'),
  array('id' => '360','codigo_conta' => '544','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM CONDUÇÃO','tipo_conta' => 'A'),
  array('id' => '361','codigo_conta' => '545','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM VEICULOS','tipo_conta' => 'A'),
  array('id' => '362','codigo_conta' => '546','classificacao_conta' => '2147483647','nome_conta' => 'FRETES E CARRETOS / SERVIÇOS MOTOBOY','tipo_conta' => 'A'),
  array('id' => '363','codigo_conta' => '547','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM INTERNET','tipo_conta' => 'A'),
  array('id' => '364','codigo_conta' => '548','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM VIAGENS','tipo_conta' => 'A'),
  array('id' => '365','codigo_conta' => '551','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS DIVERSAS','tipo_conta' => 'A'),
  array('id' => '366','codigo_conta' => '574','classificacao_conta' => '2147483647','nome_conta' => 'ORGÃO DE CLASSE','tipo_conta' => 'A'),
  array('id' => '367','codigo_conta' => '576','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS INDEDUTÍVEIS','tipo_conta' => 'A'),
  array('id' => '368','codigo_conta' => '581','classificacao_conta' => '2147483647','nome_conta' => 'BONIFICAÇÕES','tipo_conta' => 'A'),
  array('id' => '369','codigo_conta' => '583','classificacao_conta' => '2147483647','nome_conta' => 'SERVIÇOS GRAFICOS','tipo_conta' => 'A'),
  array('id' => '370','codigo_conta' => '602','classificacao_conta' => '2147483647','nome_conta' => 'FEIRAS E EVENTOS','tipo_conta' => 'A'),
  array('id' => '371','codigo_conta' => '603','classificacao_conta' => '2147483647','nome_conta' => 'SUPRIMENTO DE INFORMATICA','tipo_conta' => 'A'),
  array('id' => '372','codigo_conta' => '612','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS C/COMBUSTIVEL','tipo_conta' => 'A'),
  array('id' => '373','codigo_conta' => '621','classificacao_conta' => '2147483647','nome_conta' => 'FESTAS/CONFRATERNIZAÇÕES','tipo_conta' => 'A'),
  array('id' => '374','codigo_conta' => '727','classificacao_conta' => '2147483647','nome_conta' => 'SERVIÇOS INSTALAÇÃO/SUPORTE TECNICO - SOFTWARES','tipo_conta' => 'A'),
  array('id' => '375','codigo_conta' => '756','classificacao_conta' => '2147483647','nome_conta' => 'DESPESA COM IMOBILIZADO','tipo_conta' => 'A'),
  array('id' => '376','codigo_conta' => '339','classificacao_conta' => '32202','nome_conta' => 'ALUGUÉIS E ARRENDAMENTOS','tipo_conta' => 'S'),
  array('id' => '377','codigo_conta' => '341','classificacao_conta' => '2147483647','nome_conta' => 'ALUGUÉIS DE IMÓVEIS','tipo_conta' => 'A'),
  array('id' => '378','codigo_conta' => '342','classificacao_conta' => '2147483647','nome_conta' => 'CONDOMÍNIO','tipo_conta' => 'A'),
  array('id' => '379','codigo_conta' => '738','classificacao_conta' => '2147483647','nome_conta' => 'ALUGUEL DE VEICULO','tipo_conta' => 'A'),
  array('id' => '380','codigo_conta' => '563','classificacao_conta' => '323','nome_conta' => 'DESPESAS COMERCIAIS','tipo_conta' => 'S'),
  array('id' => '381','codigo_conta' => '564','classificacao_conta' => '32301','nome_conta' => 'DESPESAS COMERCIAIS','tipo_conta' => 'S'),
  array('id' => '382','codigo_conta' => '550','classificacao_conta' => '2147483647','nome_conta' => 'DOAÇÕES E BRINDES','tipo_conta' => 'A'),
  array('id' => '383','codigo_conta' => '552','classificacao_conta' => '2147483647','nome_conta' => 'PROPAGANDA E PUBLICIDADE','tipo_conta' => 'A'),
  array('id' => '384','codigo_conta' => '568','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS DE CARTÓRIO / JUCEMG','tipo_conta' => 'A'),
  array('id' => '385','codigo_conta' => '569','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM PROCESSOS ','tipo_conta' => 'A'),
  array('id' => '386','codigo_conta' => '622','classificacao_conta' => '2147483647','nome_conta' => 'PATROCINIOS','tipo_conta' => 'A'),
  array('id' => '387','codigo_conta' => '648','classificacao_conta' => '2147483647','nome_conta' => 'DESPESAS COM CARTÃO DE CREDITO','tipo_conta' => 'A'),
  array('id' => '388','codigo_conta' => '340','classificacao_conta' => '324','nome_conta' => 'DESPESAS FINANCEIRAS','tipo_conta' => 'S'),
  array('id' => '389','codigo_conta' => '367','classificacao_conta' => '32401','nome_conta' => 'DESPESAS FINANCEIRAS','tipo_conta' => 'S'),
  array('id' => '390','codigo_conta' => '368','classificacao_conta' => '2147483647','nome_conta' => 'JUROS PASSIVOS','tipo_conta' => 'A'),
  array('id' => '391','codigo_conta' => '369','classificacao_conta' => '2147483647','nome_conta' => 'DESPESA COM IOF','tipo_conta' => 'A'),
  array('id' => '392','codigo_conta' => '370','classificacao_conta' => '2147483647','nome_conta' => 'VARIAÇÕES CAMBIAIS PASSIVAS','tipo_conta' => 'A'),
  array('id' => '393','codigo_conta' => '371','classificacao_conta' => '2147483647','nome_conta' => 'DESCONTOS CONCEDIDOS','tipo_conta' => 'A'),
  array('id' => '394','codigo_conta' => '372','classificacao_conta' => '2147483647','nome_conta' => 'JUROS DE MORA','tipo_conta' => 'A'),
  array('id' => '395','codigo_conta' => '373','classificacao_conta' => '2147483647','nome_conta' => 'JUROS SOBRE CAPITAL PRÓPRIO','tipo_conta' => 'A'),
  array('id' => '396','codigo_conta' => '374','classificacao_conta' => '2147483647','nome_conta' => 'TAXAS E COMISSÕES BANCÁRIAS','tipo_conta' => 'A'),
  array('id' => '397','codigo_conta' => '375','classificacao_conta' => '2147483647','nome_conta' => 'JUROS SOBRE EMPRÉSTIMOS E FINANCIAMENTOS','tipo_conta' => 'A'),
  array('id' => '398','codigo_conta' => '577','classificacao_conta' => '2147483647','nome_conta' => 'ANUIDADE CARTÃO DE CRÉDITO','tipo_conta' => 'A'),
  array('id' => '399','codigo_conta' => '343','classificacao_conta' => '325','nome_conta' => 'DESPESAS TRIBUTÁRIAS','tipo_conta' => 'S'),
  array('id' => '400','codigo_conta' => '345','classificacao_conta' => '32501','nome_conta' => 'IMPOSTOS, TAXAS E CONTRIBUIÇÕES','tipo_conta' => 'S'),
  array('id' => '401','codigo_conta' => '346','classificacao_conta' => '2147483647','nome_conta' => 'TAXAS MUNICIPAIS','tipo_conta' => 'A'),
  array('id' => '402','codigo_conta' => '347','classificacao_conta' => '2147483647','nome_conta' => 'TAXAS ESTADUAIS','tipo_conta' => 'A'),
  array('id' => '403','codigo_conta' => '348','classificacao_conta' => '2147483647','nome_conta' => 'IPTU','tipo_conta' => 'A'),
  array('id' => '404','codigo_conta' => '349','classificacao_conta' => '2147483647','nome_conta' => 'IPVA - DPVAT','tipo_conta' => 'A'),
  array('id' => '405','codigo_conta' => '350','classificacao_conta' => '2147483647','nome_conta' => 'TAXAS DIVERSAS','tipo_conta' => 'A'),
  array('id' => '406','codigo_conta' => '351','classificacao_conta' => '2147483647','nome_conta' => 'ICMS DIFERENÇA DE ALÍQUOTA','tipo_conta' => 'A'),
  array('id' => '407','codigo_conta' => '352','classificacao_conta' => '2147483647','nome_conta' => 'MULTAS ','tipo_conta' => 'A'),
  array('id' => '408','codigo_conta' => '557','classificacao_conta' => '2147483647','nome_conta' => 'IMPOSTO DE RENDA','tipo_conta' => 'A'),
  array('id' => '409','codigo_conta' => '558','classificacao_conta' => '2147483647','nome_conta' => 'CONTRIBUIÇÃO SOCIAL','tipo_conta' => 'A'),
  array('id' => '410','codigo_conta' => '570','classificacao_conta' => '2147483647','nome_conta' => 'CONTRIBUIÇÃO SINDICAL','tipo_conta' => 'A'),
  array('id' => '411','codigo_conta' => '571','classificacao_conta' => '2147483647','nome_conta' => 'ISS SOBRE SERVICOS','tipo_conta' => 'A'),
  array('id' => '412','codigo_conta' => '344','classificacao_conta' => '326','nome_conta' => 'OUTRAS DESPESAS OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '413','codigo_conta' => '376','classificacao_conta' => '32601','nome_conta' => 'OUTRAS DESPESAS OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '414','codigo_conta' => '377','classificacao_conta' => '2147483647','nome_conta' => 'PROVISÕES P/ PERDAS E A JUSTES DE ATIVOS','tipo_conta' => 'A'),
  array('id' => '415','codigo_conta' => '378','classificacao_conta' => '2147483647','nome_conta' => 'EQUIVALÊNCIA  PATRIMONIAL','tipo_conta' => 'A'),
  array('id' => '416','codigo_conta' => '632','classificacao_conta' => '32602','nome_conta' => 'PERDAS NO RECEBIMENTO','tipo_conta' => 'S'),
  array('id' => '417','codigo_conta' => '633','classificacao_conta' => '2147483647','nome_conta' => 'PERDA NO RECEBIMENTO','tipo_conta' => 'A'),
  array('id' => '418','codigo_conta' => '380','classificacao_conta' => '33','nome_conta' => 'DESPESAS NÃO OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '419','codigo_conta' => '381','classificacao_conta' => '331','nome_conta' => 'RESULTADOS NÃO OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '420','codigo_conta' => '383','classificacao_conta' => '33101','nome_conta' => 'RESULTADOS NEGATIVOS NA ALIEN. DE INVEST','tipo_conta' => 'S'),
  array('id' => '421','codigo_conta' => '384','classificacao_conta' => '2147483647','nome_conta' => 'PERDAS NA ALIENAÇÃO EM PAR. EM COLIGADAS','tipo_conta' => 'A'),
  array('id' => '422','codigo_conta' => '385','classificacao_conta' => '33102','nome_conta' => 'RESULTADO NEGATIVO NA ALIENAÇÃO DO IMOB.','tipo_conta' => 'S'),
  array('id' => '423','codigo_conta' => '386','classificacao_conta' => '2147483647','nome_conta' => 'PERDAS NA ALIENAÇÃO DE IMOBILIZADO','tipo_conta' => 'A'),
  array('id' => '424','codigo_conta' => '390','classificacao_conta' => '33103','nome_conta' => 'RESULTADO NEGATIVO DE SINISTRO COM IMOB.','tipo_conta' => 'S'),
  array('id' => '425','codigo_conta' => '391','classificacao_conta' => '2147483647','nome_conta' => 'PERDAS EM SINISTROS COM IMOBILIZADO','tipo_conta' => 'A'),
  array('id' => '426','codigo_conta' => '392','classificacao_conta' => '33104','nome_conta' => 'OUTRAS BAIXAS DO ATIVO PERMANENTE','tipo_conta' => 'S'),
  array('id' => '427','codigo_conta' => '393','classificacao_conta' => '2147483647','nome_conta' => 'BAIXAS DE INVESTIMENTOS PERMANENTES','tipo_conta' => 'A'),
  array('id' => '428','codigo_conta' => '394','classificacao_conta' => '2147483647','nome_conta' => 'BAIXAS DE IMOBILIZADO','tipo_conta' => 'A'),
  array('id' => '429','codigo_conta' => '553','classificacao_conta' => '33105','nome_conta' => 'OUTRAS DESPESAS NÃO OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '430','codigo_conta' => '554','classificacao_conta' => '2147483647','nome_conta' => 'OUTRAS DESPESAS','tipo_conta' => 'A'),
  array('id' => '431','codigo_conta' => '555','classificacao_conta' => '2147483647','nome_conta' => 'BRINDES','tipo_conta' => 'A'),
  array('id' => '432','codigo_conta' => '399','classificacao_conta' => '2147483647','nome_conta' => 'OUTRAS PARTICIPAÇÕES SOCIETÁRIAS','tipo_conta' => 'A'),
  array('id' => '433','codigo_conta' => '400','classificacao_conta' => '33106','nome_conta' => 'PERDAS POR FALTA NO INVENTÁRIO','tipo_conta' => 'S'),
  array('id' => '434','codigo_conta' => '401','classificacao_conta' => '2147483647','nome_conta' => 'PERDAS POR FALTA NO INVENTÁRIO','tipo_conta' => 'A'),
  array('id' => '435','codigo_conta' => '402','classificacao_conta' => '4','nome_conta' => 'CONTAS DE RESULTADO - RECEITAS','tipo_conta' => 'S'),
  array('id' => '436','codigo_conta' => '403','classificacao_conta' => '41','nome_conta' => 'RECEITAS OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '437','codigo_conta' => '404','classificacao_conta' => '411','nome_conta' => 'RECEITA BRUTA DE VENDAS E SERVIÇOS','tipo_conta' => 'S'),
  array('id' => '438','codigo_conta' => '405','classificacao_conta' => '41101','nome_conta' => 'RECEITA BRUTAS DE VENDAS E MERCADORIAS','tipo_conta' => 'S'),
  array('id' => '439','codigo_conta' => '408','classificacao_conta' => '2147483647','nome_conta' => 'VENDA DE MERCADORIAS','tipo_conta' => 'A'),
  array('id' => '440','codigo_conta' => '409','classificacao_conta' => '2147483647','nome_conta' => 'VENDA DE MERCADORIAS NO MERCADO EXTERNO','tipo_conta' => 'A'),
  array('id' => '441','codigo_conta' => '410','classificacao_conta' => '41102','nome_conta' => 'RECEITA DE PRESTAÇÃO DE SERVIÇOS','tipo_conta' => 'S'),
  array('id' => '442','codigo_conta' => '411','classificacao_conta' => '2147483647','nome_conta' => 'SERVIÇOS PRESTADOS','tipo_conta' => 'A'),
  array('id' => '443','codigo_conta' => '412','classificacao_conta' => '2147483647','nome_conta' => 'SERVIÇOS PRESTADO MERCADO EXTERNO','tipo_conta' => 'A'),
  array('id' => '444','codigo_conta' => '413','classificacao_conta' => '412','nome_conta' => '(-) DEDUÇÕES DA RECEITA BRUTA','tipo_conta' => 'S'),
  array('id' => '445','codigo_conta' => '414','classificacao_conta' => '41201','nome_conta' => '(-) CANCELAMENTO E DEVOLUÇÕES','tipo_conta' => 'S'),
  array('id' => '446','codigo_conta' => '415','classificacao_conta' => '2147483647','nome_conta' => '(-) DEVOLUÇÃO DE VENDAS ','tipo_conta' => 'A'),
  array('id' => '447','codigo_conta' => '416','classificacao_conta' => '2147483647','nome_conta' => '(-) CANCELAMENTO SERVIÇOS','tipo_conta' => 'A'),
  array('id' => '448','codigo_conta' => '419','classificacao_conta' => '41202','nome_conta' => '(-) DESCONTOS INCONDICIONAIS','tipo_conta' => 'S'),
  array('id' => '449','codigo_conta' => '420','classificacao_conta' => '2147483647','nome_conta' => '(-) DESCONTO VENDA DE PRODUTOS','tipo_conta' => 'A'),
  array('id' => '450','codigo_conta' => '421','classificacao_conta' => '2147483647','nome_conta' => '(-) DESCONTO SERVIÇOS PRESTADOS','tipo_conta' => 'A'),
  array('id' => '451','codigo_conta' => '424','classificacao_conta' => '41203','nome_conta' => '(-) IMPOSTOS SOBRE VENDAS E SERVIÇOS','tipo_conta' => 'S'),
  array('id' => '452','codigo_conta' => '425','classificacao_conta' => '2147483647','nome_conta' => '(-) IPI','tipo_conta' => 'A'),
  array('id' => '453','codigo_conta' => '426','classificacao_conta' => '2147483647','nome_conta' => '(-) ICMS','tipo_conta' => 'A'),
  array('id' => '454','codigo_conta' => '427','classificacao_conta' => '2147483647','nome_conta' => '(-) ISS','tipo_conta' => 'A'),
  array('id' => '455','codigo_conta' => '428','classificacao_conta' => '2147483647','nome_conta' => '(-) COFINS','tipo_conta' => 'A'),
  array('id' => '456','codigo_conta' => '429','classificacao_conta' => '2147483647','nome_conta' => '(-) PIS','tipo_conta' => 'A'),
  array('id' => '457','codigo_conta' => '480','classificacao_conta' => '2147483647','nome_conta' => '(-) SIMPLES','tipo_conta' => 'A'),
  array('id' => '458','codigo_conta' => '430','classificacao_conta' => '413','nome_conta' => 'RECEITAS FINANCEIRAS','tipo_conta' => 'S'),
  array('id' => '459','codigo_conta' => '431','classificacao_conta' => '41301','nome_conta' => 'JUROS E DESCONTOS','tipo_conta' => 'S'),
  array('id' => '460','codigo_conta' => '432','classificacao_conta' => '2147483647','nome_conta' => 'JUROS DE APLICAÇÕES','tipo_conta' => 'A'),
  array('id' => '461','codigo_conta' => '433','classificacao_conta' => '2147483647','nome_conta' => 'JUROS ATIVOS (OUTROS)','tipo_conta' => 'A'),
  array('id' => '462','codigo_conta' => '434','classificacao_conta' => '2147483647','nome_conta' => 'DESCONTOS FINANCEIROS OBTIDOS','tipo_conta' => 'A'),
  array('id' => '463','codigo_conta' => '435','classificacao_conta' => '2147483647','nome_conta' => 'JUROS SOBRE O CAPITAL PRÓPRIO','tipo_conta' => 'A'),
  array('id' => '464','codigo_conta' => '475','classificacao_conta' => '2147483647','nome_conta' => 'MULTA','tipo_conta' => 'A'),
  array('id' => '465','codigo_conta' => '436','classificacao_conta' => '41302','nome_conta' => 'VARIAÇÕES MONETÁRIAS','tipo_conta' => 'S'),
  array('id' => '466','codigo_conta' => '437','classificacao_conta' => '2147483647','nome_conta' => 'VARIAÇÕES MONETÁRIAS ATIVAS','tipo_conta' => 'A'),
  array('id' => '467','codigo_conta' => '438','classificacao_conta' => '2147483647','nome_conta' => 'VARIAÇÕES CAMBIAIS ATIVAS','tipo_conta' => 'A'),
  array('id' => '468','codigo_conta' => '439','classificacao_conta' => '414','nome_conta' => 'RECUPERAÇÃO DE DESPESAS','tipo_conta' => 'S'),
  array('id' => '469','codigo_conta' => '440','classificacao_conta' => '41401','nome_conta' => 'RECUP. CRÉDITOS CONSIDERADOS INCOBRÁVEIS','tipo_conta' => 'S'),
  array('id' => '470','codigo_conta' => '441','classificacao_conta' => '41402','nome_conta' => 'REVERSÃO DE PROVISÕES','tipo_conta' => 'S'),
  array('id' => '471','codigo_conta' => '442','classificacao_conta' => '415','nome_conta' => 'OUTRAS RECEITAS OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '472','codigo_conta' => '443','classificacao_conta' => '41501','nome_conta' => 'RECEITAS DIVERSAS','tipo_conta' => 'S'),
  array('id' => '473','codigo_conta' => '444','classificacao_conta' => '2147483647','nome_conta' => 'ALUGUÉIS E ARRENDAMENTOS','tipo_conta' => 'A'),
  array('id' => '474','codigo_conta' => '445','classificacao_conta' => '2147483647','nome_conta' => 'VENDAS ACESSÓRIAS','tipo_conta' => 'A'),
  array('id' => '475','codigo_conta' => '446','classificacao_conta' => '2147483647','nome_conta' => 'OUTRAS RECEITAS ','tipo_conta' => 'A'),
  array('id' => '476','codigo_conta' => '447','classificacao_conta' => '2147483647','nome_conta' => 'DIVIDENDOS E LUCROS RECEBIDOS','tipo_conta' => 'A'),
  array('id' => '477','codigo_conta' => '448','classificacao_conta' => '2147483647','nome_conta' => 'REEMBOLSO DE DESPESAS','tipo_conta' => 'A'),
  array('id' => '478','codigo_conta' => '449','classificacao_conta' => '42','nome_conta' => 'RECEITAS NÃO OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '479','codigo_conta' => '450','classificacao_conta' => '421','nome_conta' => 'RESULTADOS NÃO OPERACIONAIS','tipo_conta' => 'S'),
  array('id' => '480','codigo_conta' => '451','classificacao_conta' => '42101','nome_conta' => 'RESULTADOS POSIT. NA ALIEN. DE INVESTIM','tipo_conta' => 'S'),
  array('id' => '481','codigo_conta' => '452','classificacao_conta' => '2147483647','nome_conta' => 'LUCROS NA ALIENAÇÃO DE PART. EM COLIGADA','tipo_conta' => 'A'),
  array('id' => '482','codigo_conta' => '453','classificacao_conta' => '42102','nome_conta' => 'LUCROS NA ALIENAÇÃO DE IMOBILIZADO','tipo_conta' => 'S'),
  array('id' => '483','codigo_conta' => '454','classificacao_conta' => '2147483647','nome_conta' => 'LUCROS NA ALIENAÇÃO DE IMOBILIZADO','tipo_conta' => 'A'),
  array('id' => '484','codigo_conta' => '458','classificacao_conta' => '42103','nome_conta' => 'RESULTADO DE SINISTROS COM IMOBILIZADO','tipo_conta' => 'S'),
  array('id' => '485','codigo_conta' => '459','classificacao_conta' => '2147483647','nome_conta' => 'INDENIZAÇÃO DE SINISTROS COM IMOBILIZADO','tipo_conta' => 'A'),
  array('id' => '486','codigo_conta' => '460','classificacao_conta' => '5','nome_conta' => 'CONTAS DE APURAÇÃO','tipo_conta' => 'S'),
  array('id' => '487','codigo_conta' => '461','classificacao_conta' => '51','nome_conta' => 'CUSTOS DOS PRODUTOS E SERVIÇOS VENDIDOS','tipo_conta' => 'S'),
  array('id' => '488','codigo_conta' => '462','classificacao_conta' => '511','nome_conta' => 'CUSTOS DOS PRODUTOS VENDIDOS','tipo_conta' => 'S'),
  array('id' => '489','codigo_conta' => '463','classificacao_conta' => '51101','nome_conta' => 'CUSTOS DOS PRODUTOS VENDIDOS','tipo_conta' => 'S'),
  array('id' => '490','codigo_conta' => '465','classificacao_conta' => '512','nome_conta' => 'CUSTOS DOS SERVIÇOS PRESTADOS','tipo_conta' => 'S'),
  array('id' => '491','codigo_conta' => '466','classificacao_conta' => '51201','nome_conta' => 'CUSTOS DOS SERVIÇOS PRESTADOS','tipo_conta' => 'S'),
  array('id' => '492','codigo_conta' => '468','classificacao_conta' => '513','nome_conta' => 'CUSTOS DAS MERCADORIAS VENDIDAS','tipo_conta' => 'S'),
  array('id' => '493','codigo_conta' => '469','classificacao_conta' => '51301','nome_conta' => 'CUSTOS DAS MERCADORIAS VENDIDAS','tipo_conta' => 'S'),
  array('id' => '494','codigo_conta' => '471','classificacao_conta' => '514','nome_conta' => 'APURAÇÃO DO RESULTADO DO EXERCÍCIO','tipo_conta' => 'S'),
  array('id' => '495','codigo_conta' => '472','classificacao_conta' => '51401','nome_conta' => 'APURAÇÃO DO RESULTADO DO EXERCÍCIO','tipo_conta' => 'S'),
  array('id' => '496','codigo_conta' => '473','classificacao_conta' => '2147483647','nome_conta' => 'RESULTADO DO EXERCÍCIO','tipo_conta' => 'A')
);

foreach($finance_tipo as $key){
  /**Verificar se já existe o cadastro */
  $sql = "SELECT * FROM ".db_prefix()."finance_tipo WHERE codigo_conta = ".$key['codigo_conta'];
  $query = $CI->db->query($sql);
  $result = $query->result_array();
  if(empty($result)){
    /**remover o indice id */
    unset($key['id']);
    $CI->db->insert('finance_tipo', $key);
  }
}